[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
contract = "5yynpSFAbuykSSTBGwg6E6L3J5zibfVn27e4bUqhecZJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
